version: '3'

services:
  mongo:
    image: mongo:4.0
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongodb:/data/db
    logging: &logging
      driver: json-file

  fetcher:
    build: ./permission_fetcher
    depends_on:
      - mongo
    volumes:
      - pictures:/opt/pictures
    logging:
      <<: *logging

volumes:
  mongodb:
    driver: local
  pictures:
    driver: local
