version: '3'

services:
  mongo:
    image: mongo:4.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    logging: &logging
      driver: json-file

  fetcher:
    build: ./fetcher
    depends_on:
      - mongo
    volumes:
      - pictures:/opt/pictures
    logging:
      <<: *logging

  api:
    build: ./api
    depends_on:
    - mongo
    - fetcher
    logging:
      <<: *logging

  frontend:
    build: ./frontend
    ports:
    - "80:80"
    depends_on:
    - api
    volumes:
    - pictures:/usr/share/nginx/html/static/pictures:ro
    logging:
      <<: *logging

volumes:
  mongodb:
    driver: local
  pictures:
    driver: local
