version: '3'

services:
  mongo:
    image: mongo:4.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    logging: &logging
      driver: json-file

  fetcher:
    build: ./permission_fetcher
    depends_on:
      - mongo
    volumes:
      - pictures:/opt/pictures
    logging:
      <<: *logging

  viewer:
    build: ./permission_viewer
    ports:
      - "80:8000"
    depends_on:
    - mongo
    - fetcher
    logging:
      <<: *logging

volumes:
  mongodb:
    driver: local
  pictures:
    driver: local
